/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { menuItems } from './menuData';
import { 
  Phone, 
  MapPin, 
  Clock, 
  Star, 
  ChevronLeft, 
  ChevronRight, 
  Menu, 
  X, 
  Check, 
  Heart, 
  Music, 
  Coffee, 
  Sparkles, 
  Award, 
  UtensilsCrossed, 
  ThumbsUp, 
  MessageSquare,
  Accessibility,
  Car,
  Flame,
  Wine,
  Beer,
  CreditCard,
  Baby,
  Users,
  Wifi,
  AlertTriangle,
  Search,
  Filter,
  Instagram
} from 'lucide-react';

// Path-resolved reference paths of images generated by Google AI Studio
const heroImage = '/src/assets/images/qala_divari_hero_1780303654944.png';
const kebabImage = '/src/assets/images/qala_divari_kebab_1780303675477.png';
const teaImage = '/src/assets/images/qala_divari_tea_1780303698310.png';
const interiorImage = '/src/assets/images/qala_divari_interior_1780303718606.png';
const sajImage = '/src/assets/images/qala_divari_saj_1780303742362.png';

interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  image: string;
  isPopular?: boolean;
  isChefSpecial?: boolean;
  weight?: string;
  ingredients?: string[];
}

interface AmenityItem {
  category: string;
  name: string;
  highlight: string;
  supported: boolean;
  desc?: string;
}

const amenityCategories = [
  { id: 'all', label: 'Bütün İmkanlar', icon: 'Filter' },
  { id: 'accessibility', label: 'Əlçatanlıq (Accessibility)', icon: 'Accessibility' },
  { id: 'service', label: 'Xidmət Seçimləri', icon: 'Sparkles' },
  { id: 'highlights', label: 'Önə Çыxanlar (Highlights)', icon: 'Award' },
  { id: 'popular', label: 'Məşhurluq (Popular For)', icon: 'ThumbsUp' },
  { id: 'offerings', label: 'Təkliflər (Offerings)', icon: 'UtensilsCrossed' },
  { id: 'dining', label: 'Yemək Seçimləri', icon: 'Coffee' },
  { id: 'amenities', label: 'Rahatlıqlar (Amenities)', icon: 'Wifi' },
  { id: 'atmosphere', label: 'Atmosfer & Aura', icon: 'Heart' },
  { id: 'crowd', label: 'Ziyarətçilər (Crowd)', icon: 'Users' },
  { id: 'payments', label: 'Ödəniş Metodları', icon: 'CreditCard' },
  { id: 'children', label: 'Uşaqlar və Ailə', icon: 'Baby' },
  { id: 'parking', label: 'Parkovka & Nəqliyyat', icon: 'Car' }
];

const allAmenities: AmenityItem[] = [
  // Accessibility
  { category: 'accessibility', name: 'Əlil arabası üçün uyğun dayanacaq', highlight: 'Wheelchair-accessible car park', supported: true, desc: 'Əlil arabası ilə gələn qonaqlarımız üçün ayrılmış daxili xüsusi parkinq yerləri.' },
  { category: 'accessibility', name: 'Əlil arabası üçün uyğun giriş / rampa', highlight: 'Wheelchair-accessible entrance', supported: true, desc: 'Restoranın həm terras, həm də qapalı tarixi zallarına maneəsiz daxil olmaq üçün xüsusi rampalar.' },
  { category: 'accessibility', name: 'Əlil arabası üçün uyğun oturacaq tənzimləmələri', highlight: 'Wheelchair-accessible seating', supported: true, desc: 'Geniş manevr boşluğuna və uyğun hündürlüyə malik xüsusi masa yerləri.' },
  { category: 'accessibility', name: 'Əlil arabası üçün uyğun sanitar qovşaq', highlight: 'Wheelchair-accessible toilet', supported: true, desc: 'Geniş, dəstək tutacaqları və xüsusi dördbucaqlı asan keçid qapısı olan rahat tualet.' },
  // Service options
  { category: 'service', name: 'Açıq havada masalar (Terras)', highlight: 'Outdoor seating', supported: true, desc: 'Bakı qala divarları yanında, qışda qızdırıcı ilə, yayda isə sərin dəniz mehi ilə əla terras mənzərəsi.' },
  { category: 'service', name: 'Özünlə apar xidməti', highlight: 'Takeaway', supported: true, desc: 'Bütün ləzzətli ət, sac və çay dəstgahlarımızın xüsusi qoruyucu paketlərdə ünvanına və ya özünlə götürmək üçün hazırlanması.' },
  { category: 'service', name: 'Yerində rəsmi şah xidməti', highlight: 'Dine-in', supported: true, desc: 'Klassik daş divarlarımız, tağlı zallarımız və milli naxışlar daxilində tam masaya xidmət.' },
  // Highlights
  { category: 'highlights', name: 'İsti kamin / Ocaq', highlight: 'Fireplace', supported: true, desc: 'Qış günlərində qonaqların içini isidən, köhnə üslublu kərpic kamin guşəmiz.' },
  { category: 'highlights', name: 'Geniş və keyfiyyətli pivə menyusu', highlight: 'Great beer selection', supported: true, desc: 'Milli və dünya şöhrətli süzmə, butulka pivə çeşidləri.' },
  { category: 'highlights', name: 'Özəl barmen kokteylləri', highlight: 'Great cocktails', supported: true, desc: 'Narşərab və xüsusi qədim otlardan hazırlanan şirin/turş qala kokteylləri.' },
  { category: 'highlights', name: 'Premium üyüdülmüş qəhvə', highlight: 'Great coffee', supported: true, desc: 'Təzə çəkilmiş xalis ərəb dənələri ilə hazırlanan espresso, kapuçino və türk qəhvəsi.' },
  { category: 'highlights', name: 'Əfsanəvi milli desertlər', highlight: 'Great dessert', supported: true, desc: 'Hər gün təzə bişən Şəki halvası, paxlava, şəkərbura və ətirli darçınlı firni.' },
  { category: 'highlights', name: 'Əvəzolunmaz samovar çayı dəstgahı', highlight: 'Great tea selection', supported: true, desc: 'Zəngin mürəbbələr, şirniyyatlar və meşə kəklikotusu ilə kömürlü samovarda süzülən çay.' },
  { category: 'highlights', name: 'Zəngin yerli şərab çeşidləri', highlight: 'Great wine list', supported: true, desc: 'Qəbələ, Şamaxı və Göygöl üzüm süzgəclərindən seçilmiş elit butulka şərabları.' },
  { category: 'highlights', name: 'Hər gün canlı milli muğam', highlight: 'Live music', supported: true, desc: 'Xalq sənətkarlarının ifasında canlı tar, kamança və qavalın müşayiəti ilə əsl ruh şənliyi.' },
  // Popular for
  { category: 'popular', name: 'Gündəlik səhər yeməyi dəstgahı', highlight: 'Breakfast', supported: true, desc: 'İsti sacda təndir çörəyi, süzmə, keçi pendiri, qaymaq və nehrə yağı.' },
  { category: 'popular', name: 'Dadlı biznes və ailəvi nahar', highlight: 'Lunch', supported: true, desc: 'Naharda sürətli ofisiant xidməti, sulu xörəklər və doyumlu saclar.' },
  { category: 'popular', name: 'Möhtəşəm gözəl şam yeməyi', highlight: 'Dinner', supported: true, desc: 'Terrasda ulduzların altında və tarixi zallarda unudulmaz şam saatları.' },
  { category: 'popular', name: 'Təkbaşına dincəlmək üçün sakit künclər', highlight: 'Solo dining', supported: true, desc: 'Sakit şərq musiqisi sədaları altında rahatlıqla tək dincəlmək imkanı.' },
  // Offerings
  { category: 'offerings', name: 'Alkoqollu içki xidməti', highlight: 'Alcohol', supported: true, desc: 'Barımızda hər növ yerli və xarici alkoqol çeşidləri mövcuddur.' },
  { category: 'offerings', name: 'Soyuq süzmə pivələr', highlight: 'Beer', supported: true, desc: 'Sərinkeş pivə butulkaları və çəllək süzmələri.' },
  { category: 'offerings', name: 'Kokteyl növləri', highlight: 'Cocktails', supported: true },
  { category: 'offerings', name: 'Səhər və günorta qəhvəsi', highlight: 'Coffee', supported: true },
  { category: 'offerings', name: '100% Səhih Halal qidalar', highlight: 'Halal  food', supported: true, desc: 'Restoranımızda istifadə olunan bütün ət məhsulları rəsmi Halal sertifikatlıdır və İslam qaydalarına əsasən kəsilir.' },
  { category: 'offerings', name: 'Fasiləsiz gecə yarısı yeməkləri', highlight: 'Late-night food', supported: true, desc: 'Restoranımız 24 saat fəaliyyət göstərir - gecə saat 03:00-da belə zəngin təndir və isti pitilər hazırdır.' },
  { category: 'offerings', name: 'Təbii orqanik bağ məhsulları', highlight: 'Organic dishes', supported: true, desc: 'Kəndlərdən xüsusi gətirilən təmiz kərə yağı, qatqısız göyərtilər və orqanik ətlər.' },
  { category: 'offerings', name: 'Sürətli milli qəlyanaltılar (Qutablar və s.)', highlight: 'Quick bite', supported: true },
  { category: 'offerings', name: 'Kiçik nimçələrdə milli məzələr', highlight: 'Small plates', supported: true, desc: 'Yeməkdən əvvəl stolu bəzəyən dadlı humuslar, süzmələr, sirkələr və milli kürü.' },
  { category: 'offerings', name: 'Sərt içkilər (Spirits)', highlight: 'Spirits', supported: true },
  { category: 'offerings', name: 'Xüsusi vegan variantları', highlight: 'Vegan options', supported: true, desc: 'Bitki mənşəli göy qutabları, kartoflu göbələkli saclar və qatqısız salatlar.' },
  { category: 'offerings', name: 'Vegetarianlar üçün geniş çeşid', highlight: 'Vegetarian options', supported: true, desc: 'Tərəvəz sacları, manqal salatları, pendir assortiləri və unikal isti xörəklər.' },
  { category: 'offerings', name: 'Şamil yerli və xarici şərablar', highlight: 'Wine', supported: true },
  // Dining options
  { category: 'dining', name: 'Səhər yeməyi vaxtı', highlight: 'Breakfast', supported: true },
  { category: 'dining', name: 'Əla branç (Brunch) saatları', highlight: 'Brunch', supported: true },
  { category: 'dining', name: 'Doyumlu biznes naharı (Lunch)', highlight: 'Lunch', supported: true },
  { category: 'dining', name: 'Terrasda axşam şamı (Dinner)', highlight: 'Dinner', supported: true },
  { category: 'dining', name: 'Özəl catering (Yemək paylama) xidməti', highlight: 'Catering', supported: true, desc: 'Böyük ailəvi və ya rəsmi şənliklərdə qazanda milli plovlarımızın ünvanında təşkili.' },
  { category: 'dining', name: 'Tez-pişirmə və sürətli xidmət', highlight: 'Counter service', supported: true },
  { category: 'dining', name: 'Çay və möhtəşəm şirniyyat saatı', highlight: 'Dessert', supported: true },
  { category: 'dining', name: 'Yumşaq taxt oturacaq quraşdırmaları', highlight: 'Seating', supported: true },
  { category: 'dining', name: 'Professional masaya qulluq', highlight: 'Table service', supported: true, desc: 'Sizin rahatlığınız üçün masalara rəsmi klassik geyimli professional ofisiantlarımız nəzarət edir.' },
  // Amenities
  { category: 'amenities', name: 'Gender-neytral tualetlər', highlight: 'Gender-neutral toilets', supported: true, desc: 'Rahat və müasir ümumi sanitar qovşaq sistemi.' },
  { category: 'amenities', name: 'Təmiz, steril tualet binaları', highlight: 'Toilet', supported: true, desc: 'Hər saat başı təmizlənən gigiyenik tualetlər.' },
  { category: 'amenities', name: 'Yüksək sürətli limitsiz Wi-Fi', highlight: 'Wi-Fi', supported: true },
  { category: 'amenities', name: 'Tamamilə pulsuz sürətli Wi-Fi', highlight: 'Free Wi-Fi', supported: true, desc: 'Hem qonaq zallarında, həm terrasda parolsuz dərhal qoşula biləcəyiniz internet şəbəkəsi.' },
  // Atmosphere
  { category: 'atmosphere', name: 'Gündəlik səmimi ab-hava (Casual)', highlight: 'Casual', supported: true },
  { category: 'atmosphere', name: 'İsti və doğma (Cosy) dizayn', highlight: 'Cosy', supported: true, desc: 'Klassik Şərq şamdanları, milli palas və süjetli xalçalarımız ilə ev rahatlığı.' },
  { category: 'atmosphere', name: 'Sakit təbii istirahət bölmələri', highlight: 'Quiet', supported: true },
  { category: 'atmosphere', name: 'Romantik qala və bülbül səsi', highlight: 'Romantic', supported: true, desc: 'Terrasımız axşam saatlarında sevgililər və xüsusi anlar üçün çox romantikdir.' },
  { category: 'atmosphere', name: 'Milli-modern harmoniya (Trendy)', highlight: 'Trendy', supported: true },
  { category: 'atmosphere', name: 'Elit və təntənəli mühit (Upmarket)', highlight: 'Upmarket', supported: true },
  // Crowd
  { category: 'crowd', name: 'Geniş dost və ailə qrupları', highlight: 'Groups', supported: true, desc: 'Böyük ad günləri və korporativ qrup yığıncaqları üçün masaların quraşdırılması.' },
  { category: 'crowd', name: 'Xarici turistlər üçün ideal məkan', highlight: 'Tourists', supported: true, desc: 'Bakıya gələn hər bir turistin milli mətbəxlə ilk xoş təması.' },
  { category: 'crowd', name: 'Universitet tələbələri', highlight: 'University students', supported: true },
  // Planning
  { category: 'planning', name: 'Birbaşa Giriş (Rezervasiya tələb olunmur)', highlight: 'Walk-in welcome / no booking required', supported: true, desc: 'Restoranımızın qapıları hər kəsə 24 saat açıqdır. Heç bir rezervasiya etmədən birbaşa gələrək boş yerlərə otura bilərsiniz!' },
  // Payments
  { category: 'payments', name: 'Visa & MasterCard kredit kartları', highlight: 'Credit cards', supported: true },
  { category: 'payments', name: 'Debet və yerli maaş kartları', highlight: 'Debit cards', supported: true },
  { category: 'payments', name: 'NFC mobil ödənişləri (Apple/Google Pay)', highlight: 'NFC mobile payments', supported: true, desc: 'Telefonunuzu və ya saatınızı terminala yaxınlaşdıraraq dərhal sürətli təmassız ödəniş imkanı.' },
  // Children
  { category: 'children', name: 'Uşaqları ilə gələn ailələr üçün tam rahat', highlight: 'Good for kids', supported: true },
  { category: 'children', name: 'Uşaq ad günlərinin rəngarəng təşkili', highlight: 'Good for kids birthday', supported: true, desc: 'Sürpriz tortlar, uşaq bəzəkləri və səs effekti təşkilatçılığı.' },
  { category: 'children', name: 'Uşaqlar üçün xüsusi uca oturacaqlar', highlight: 'High chairs', supported: true, desc: 'Balacaların təhlükəsiz və rahat şəkildə masada yemək yeməsi üçün uşaq stulları.' },
  { category: 'children', name: 'Vitaminli rəngarəng uşaq menyusu', highlight: 'Kids\' menu', supported: true, desc: 'Uşaqların asan həzm edəcəyi, canayaxın və maraqlı formalı yeməklər.' },
  // Parking
  { category: 'parking', name: 'Küçədə pulsuz parklanma imkanı', highlight: 'Free of charge street parking', supported: true, desc: 'Kiçik Qala döngəsi boyu ayrılmış ödənişsiz kənar yol parkinqi.' },
  { category: 'parking', name: 'Ərazidə pulsuz dayanacaq sahəsi', highlight: 'Free parking lot', supported: true },
  { category: 'parking', name: 'Yaxınlıqda rəsmi ödənişli parkinq', highlight: 'Paid parking lot', supported: true, desc: 'Sakin avtomobil qoruyucuları ilə təchiz olunmuş nəzarətli yaxın ödənişli park yerləri.' },
  { category: 'parking', name: 'Axşam pik saatlarında park yeri sıxlığı', highlight: 'Difficult to find a space', supported: false, desc: 'DİQQƏT: Axşam saatlarında (xüsusən muğam gecələri olan 20:00-22:00 arası) İçərişəhərdə boş park yeri tapmaq çətin ola bilər. Taksi ilə gəlməyinizi və ya bir qədər erkən gəlməyinizi tövsiyə edirik.' }
];

export default function App() {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [activeCategory, setActiveCategory] = useState('all');
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 12;
  const [favorites, setFavorites] = useState<string[]>([]);
  const [selectedMenuItem, setSelectedMenuItem] = useState<MenuItem | null>(null);
  
  // Gallery slider control
  const [currentSlide, setCurrentSlide] = useState(0);

  // Load favorites from localStorage
  useEffect(() => {
    const savedFavs = localStorage.getItem('qala_divari_favorites');
    if (savedFavs) {
      try {
        setFavorites(JSON.parse(savedFavs));
      } catch (e) {
        console.error(e);
      }
    }
  }, []);

  // Update favorites helper
  const toggleFavorite = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    let newFavs;
    if (favorites.includes(id)) {
      newFavs = favorites.filter(favId => favId !== id);
    } else {
      newFavs = [...favorites, id];
    }
    setFavorites(newFavs);
    localStorage.setItem('qala_divari_favorites', JSON.stringify(newFavs));
  };

  // Slider controls
  const slides = [
    {
      image: heroImage,
      title: "Möhtəşəm Terras Mənzərəsi",
      desc: "İçərişəhərin qədim qala divarları yanında, Bakının alov qüllələrinin mənzərəsi ilə ləzzətli axşam yeməyi."
    },
    {
      image: interiorImage,
      title: "Tarixi Qapalı Zallar",
      desc: "Tağvari tavanlar, əsl daş divarlar və milli naxışlı xalçalarımız ilə qədim Şərq ab-havasını hiss edin."
    },
    {
      image: sajImage,
      title: "Ənənəvi Sac Yeməkləri",
      desc: "Köz üzərində xüsusi dəmirdən hazırlanmış sacda dadlı quzu əti və təzə bağ tərəvəzlərinin harmoniyası."
    },
    {
      image: teaImage,
      title: "Əsl Bakı Çay Dəstgahı",
      desc: "Samovarda dəmlənmiş ətirli kəklikotulu çay, çeşidli mürəbbələr və əfsanəvi Bakı paxlavası."
    },
    {
      image: "https://lh3.googleusercontent.com/p/AF1QipPj4ogfDRFEmnIZPzDfwEBAPKY25FSvQC81qFNP=w1080-h1080-k-no",
      title: "Qala Divarı Eksteryer",
      desc: "Tarixi abidələrin kənarındakı daş divarlar."
    },
    {
      image: "https://lh3.googleusercontent.com/p/AF1QipOczV1-9UZsTRQ4nxylJJI0ZECfKwnVqDc-cdaA=w1080-h1080-k-no",
      title: "Açıq Hava Terras",
      desc: "Rahat və gözəl estetik mühit."
    },
    {
      image: "https://lh3.googleusercontent.com/p/AF1QipOWGEgccFpaWibCqoiQIgmghoyCwEjDUNEpHzRh=w1080-h1080-k-no",
      title: "İsti Atmosfer",
      desc: "Əla aydınlatma, ləziz ab-hava və rahatlıq."
    },
    {
      image: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAECvwXtsi3QlqjXC_qYaG3WQ6ATTAJfvD5yx_S_oZY6g9DYzJdcuMeln-DXNz2dl5W036ppulrg2lOh5TflPiAUC5vrZwftyN_klIxI43sKSbhF3RRYZSPmxiXQy26E5dSRZ7BsxDOT2uMf=w1080-h1080-k-no",
      title: "Qədim Qala Mühiti",
      desc: "Xüsusi guşələr və dekorasiyalar."
    },
    {
      image: "https://lh3.googleusercontent.com/p/AF1QipNyFp8tJGVuxjAOWUlSuCQI7IHwE0RUyICjLcep=w1080-h1080-k-no",
      title: "Milli Yemək Süfrəsi",
      desc: "Qonaqlar üçün xüsusi dizayn edilmiş stollar."
    },
    {
      image: "https://lh3.googleusercontent.com/p/AF1QipMcr5PD7dY399nLNWRD9RMFiJ2msWdmtPH_x8u5=w1080-h1080-k-no",
      title: "Unudulmaz Anlar",
      desc: "Dostlarla və ailə ilə ən gözəl anlar qeyd etmək üçün məkan."
    }
  ];

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev + 1) % slides.length);
  };

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev - 1 + slides.length) % slides.length);
  };

  // Menu items array with detailed Azerbaijani translations and prices, imported dynamically
  // containing all 223 dishes synchronized from cafetap.az Listing
  const filteredMenuItems = activeCategory === 'all' 
    ? menuItems 
    : menuItems.filter(item => item.category === activeCategory);

  const totalPages = Math.ceil(filteredMenuItems.length / itemsPerPage);
  const paginatedItems = filteredMenuItems.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  return (
    <div id="qala-app-container" className="min-h-screen bg-cream text-stone-dark font-sans selection:bg-gold selection:text-stone-dark antialiased transition-colors duration-300">
      
      {/* 24/7 Global top bar indicator */}
      <div id="top-notification-bar" className="bg-[#1C0F01] text-[#E9C967] text-xs py-2 px-4 flex flex-wrap justify-between items-center text-center gap-2 border-b border-gold/10 z-50 relative">
        <div className="flex items-center gap-2 mx-auto sm:mx-0">
          <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse inline-block"></span>
          <span className="font-semibold tracking-wide uppercase">● İNDİ AÇIQDIR (24/7)</span>
          <span className="opacity-60 hidden md:inline">| Qədim İçərişəhərdə Tarixin Dadı</span>
        </div>
        <div className="flex items-center gap-6 mx-auto sm:mx-0 font-medium">
          <a href="tel:+994505555051" className="flex items-center gap-1 hover:text-white transition">
            <Phone className="w-3.5 h-3.5 text-gold" />
            <span>+994 50 555 50 51</span>
          </a>
          <span className="hidden sm:inline flex items-center gap-1">
            <Star className="w-3.5 h-3.5 text-gold fill-gold" />
            <span className="font-bold">4.8 Google Reytinqi</span>
          </span>
        </div>
      </div>

      {/* Main Navigation Header */}
      <header id="main-navigation-header" className="sticky top-0 bg-[#2C1A04]/96 backdrop-blur-md border-b border-gold/10 z-40 transition-all">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex justify-between items-center">
          
          {/* Logo Brand area */}
          <a href="#home" id="brand-logo" className="flex items-center gap-3 group">
            <div className="w-11 h-11 md:w-12 md:h-12 rounded-full border-2 border-gold flex items-center justify-center shadow-lg transition duration-300 group-hover:border-gold-light group-hover:shadow-[0_0_12px_rgba(212,175,55,0.4)] overflow-hidden shrink-0 bg-white">
              <img src="https://cdn.cafepos.az/storage/restaurants/64621e1e0c827.jpg" alt="Qala Divarı Logo" className="w-full h-full object-cover" />
            </div>
            <div>
              <span className="font-serif text-xl sm:text-2xl font-bold tracking-wider text-cream block group-hover:text-gold transition">QALA DİVARI</span>
              <span className="text-[10px] tracking-[0.25em] text-gold uppercase block -mt-1">RESTORAN • 24/7</span>
            </div>
          </a>

          {/* Desktop Navigation Links */}
          <nav id="desktop-nav" className="hidden lg:flex items-center gap-8">
            <a href="#home" className="text-cream/80 hover:text-gold font-medium text-sm tracking-wide transition">Ana Səhifə</a>
            <a href="#our-history" className="text-cream/80 hover:text-gold font-medium text-sm tracking-wide transition">Haqqımızda</a>
            <a href="#menu" className="text-cream/80 hover:text-gold font-medium text-sm tracking-wide transition">Milli Menyu</a>
            <a href="#gallery" className="text-cream/80 hover:text-gold font-medium text-sm tracking-wide transition">Qalereya</a>
            <a href="#contact" className="text-cream/80 hover:text-gold font-medium text-sm tracking-wide transition">Əlaqə</a>
          </nav>

          {/* Quick contact trigger button */}
          <div id="header-action-group" className="hidden sm:flex items-center gap-4">
            <a 
              href="https://www.instagram.com/qala_divari/"
              target="_blank" rel="noopener noreferrer"
              className="w-11 h-11 lg:w-10 lg:h-10 rounded-full bg-[#2C1A04] border border-gold/20 hover:border-gold hover:bg-gold hover:text-stone-dark flex items-center justify-center text-gold transition duration-300 transform hover:scale-110"
              aria-label="Instagram"
            >
              <Instagram className="w-5 h-5 lg:w-4 lg:h-4" />
            </a>
            <a 
              href="tel:+994505555051" 
              id="cta-phone"
              className="bg-gold hover:bg-gold-light text-stone-dark hover:scale-[1.03] active:scale-[0.98] font-bold text-sm tracking-wider px-6 py-3 rounded-md shadow-md shadow-[#231503]/50 flex items-center gap-2 transition duration-300"
            >
              <Phone className="w-4 h-4" />
              +994 50 555 50 51
            </a>
          </div>

          {/* Hamburger Menu Mobile Button */}
          <button 
            id="mobile-menu-trigger"
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            className="lg:hidden p-2 text-gold hover:text-cream focus:outline-none"
            aria-label="Menyu"
          >
            {isMobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
          </button>

        </div>
      </header>

      {/* Mobile Drawer Menu Overlaid Navigation */}
      {isMobileMenuOpen && (
        <div id="mobile-nav-panel" className="lg:hidden fixed inset-0 top-[114px] bg-[#2C1A04] z-30 transition-all duration-300 animate-fadeIn overflow-y-auto">
          <div className="px-6 py-8 space-y-6 flex flex-col justify-between h-[calc(100vh-114px)] bg-[#2C1A04]">
            <div className="space-y-4">
              <a 
                href="#home" 
                onClick={() => setIsMobileMenuOpen(false)}
                className="block text-xl font-medium text-cream border-b border-gold/10 pb-2 hover:text-gold"
              >
                Ana Səhifə
              </a>
              <a 
                href="#our-history" 
                onClick={() => setIsMobileMenuOpen(false)}
                className="block text-xl font-medium text-cream border-b border-gold/10 pb-2 hover:text-gold"
              >
                Haqqımızda
              </a>
              <a 
                href="#menu" 
                onClick={() => setIsMobileMenuOpen(false)}
                className="block text-xl font-medium text-cream border-b border-gold/10 pb-2 hover:text-gold"
              >
                Milli Menyu
              </a>
              <a 
                href="#gallery" 
                onClick={() => setIsMobileMenuOpen(false)}
                className="block text-xl font-medium text-cream border-b border-gold/10 pb-2 hover:text-gold"
              >
                Qalereya
              </a>
              <a 
                href="#contact" 
                onClick={() => setIsMobileMenuOpen(false)}
                className="block text-xl font-medium text-cream border-b border-gold/10 pb-2 hover:text-gold"
              >
                Əlaqə
              </a>
            </div>

            <div className="space-y-4 pt-6 border-t border-gold/10">
              <div className="flex flex-col gap-2">
                <span className="text-gold text-xs tracking-widest block font-bold uppercase">ƏLAQƏ</span>
                <a href="tel:+994505555051" className="text-cream text-lg font-semibold flex items-center gap-2">
                  <Phone className="w-4 h-4 text-gold" /> +994 50 555 50 51
                </a>
                <span className="text-cream/60 text-xs flex items-center gap-2">
                  <MapPin className="w-4 h-4 text-gold shrink-0" /> Kiçik Qala döngəsi 124, İçərişəhər, Bakı
                </span>
              </div>

              <div className="flex gap-2">
                <a 
                  href="tel:+994505555051"
                  onClick={() => setIsMobileMenuOpen(false)}
                  className="w-full text-center bg-gold hover:bg-gold-light text-stone-dark font-bold text-sm py-3 rounded-md shadow-md tracking-wider flex items-center justify-center gap-2 transition"
                >
                  <Phone className="w-4 h-4" /> ZƏNG ET
                </a>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Interactive Main Hero Section */}
      <section id="home" className="relative min-h-[92vh] flex items-center justify-center overflow-hidden bg-stone-dark">
        
        {/* Ambient Darkened Image layer with pure CSS overlay */}
        <div className="absolute inset-0 z-0">
          <img 
            src={heroImage} 
            alt="Qala Divarı outdoor terrace looking over Baku sunset" 
            className="w-full h-full object-cover object-center scale-105 filter brightness-45 contrast-105"
          />
          {/* Authentic vignette & glow overlays */}
          <div className="absolute inset-0 bg-gradient-to-t from-stone-dark via-[#1F1203]/70 to-[#2C1A04]/40"></div>
          <div className="absolute inset-0 bg-radial-vignette opacity-60"></div>
        </div>

        {/* Decorative elements */}
        <div className="absolute left-4 top-24 opacity-10 hidden xl:block w-32 h-48 border-l border-b border-gold rounded-bl-3xl"></div>
        <div className="absolute right-4 bottom-12 opacity-10 hidden xl:block w-32 h-48 border-r border-t border-gold rounded-tr-3xl"></div>

        {/* Main hero contents container */}
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="relative max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-20 text-center z-10"
        >
          
          {/* Subtle star & indicator */}
          <motion.div 
            initial={{ scale: 0.8, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.8 }}
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-gold/10 border border-gold/30 backdrop-blur-sm mb-6"
          >
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
            <span className="text-[11px] sm:text-xs text-[#E9C967] font-semibold tracking-wider uppercase">● 24/7 AÇIQLIQ VƏ MUĞAM GECƏLƏRİ</span>
          </motion.div>

          <p className="text-gold font-serif text-lg sm:text-xl tracking-widest italic mb-3">
            Qədim İçərişəhərdə
          </p>

          <h1 className="font-serif text-4xl sm:text-6xl md:text-7xl font-bold text-cream tracking-tight leading-tight mb-6">
            Tarixin dadı, <br />
            <span className="text-gold font-serif text-shadow-gold">Bakının ürəyində</span>
          </h1>

          <p className="max-w-2xl mx-auto text-sm sm:text-lg text-cream/80 leading-relaxed mb-10 font-normal">
            Qala Divarı restoranı yüzillik sirli qala mühitində sizi milli Azərbaycan mətbəxinin orijinal dadlarını, közdə bişən təamları və unudulmaz canlı muğam dastanlarını kəşf etmeyə dəvət edir.
          </p>

          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 1 }}
            className="flex flex-col sm:flex-row justify-center items-center gap-4"
          >
            <a 
              href="#menu"
              className="w-full sm:w-auto bg-gold hover:bg-gold-light active:scale-95 text-stone-dark font-bold tracking-widest text-sm px-8 py-4 rounded-md shadow-lg shadow-[#1C0F01]/60 transition-all duration-300 uppercase"
            >
              MİLLİ MENYUYA BAX
            </a>
            <a 
              href="tel:+994505555051"
              className="w-full sm:w-auto text-cream border border-cream/30 hover:border-gold hover:text-gold hover:bg-stone-dark/40 backdrop-blur-sm tracking-widest text-sm px-8 py-4 rounded-md transition-all duration-300 flex items-center justify-center gap-2"
            >
              <Phone className="w-4 h-4 text-gold" /> ƏLAQƏ SAXLA
            </a>
          </motion.div>

          {/* Hero properties summary widgets */}
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1, delay: 1.2 }}
            className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto mt-16 pt-8 border-t border-cream/10 text-cream/70"
          >
            <div className="text-center p-2">
              <span className="block text-2xl font-serif font-bold text-gold">24/7</span>
              <span className="text-[11px] uppercase tracking-widest text-cream/50 font-medium">Həmişə Açıqdır</span>
            </div>
            <div className="text-center p-2 border-l border-cream/10">
              <span className="block text-2xl font-serif font-bold text-gold">4.8</span>
              <span className="text-[11px] uppercase tracking-widest text-cream/50 font-medium font-semibold">Google Reytinq</span>
            </div>
            <div className="text-center p-2 border-l border-cream/10 md:border-l">
              <span className="block text-2xl font-serif font-bold text-gold">Hər Gün</span>
              <span className="text-[11px] uppercase tracking-widest text-cream/50 font-medium font-semibold font-medium">Canlı Muğam</span>
            </div>
            <div className="text-center p-2 border-l border-cream/10">
              <span className="block text-2xl font-serif font-bold text-gold">Terras</span>
              <span className="text-[11px] uppercase tracking-widest text-cream/50 font-medium text-xs font-semibold">Gözəl Mənzərə</span>
            </div>
          </motion.div>

        </motion.div>

        {/* Ambient geometric arc matching ancient design */}
        <div className="absolute bottom-0 left-0 right-0 h-4 bg-gradient-to-t from-cream to-transparent z-10"></div>
      </section>

      {/* Haqqımızda & Özəlliklər Section (History & Concept) */}
      <section id="our-history" className="py-24 bg-cream relative overflow-hidden">
        
        {/* Background decorative vector */}
        <div className="absolute left-[5%] top-[10%] opacity-2 w-72 h-72 rounded-full border-2 border-stone-dark/30 select-none pointer-events-none"></div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            
            {/* Visuals - Double Image layout */}
            <motion.div 
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="lg:col-span-6 relative"
            >
              <div className="relative z-10 overflow-hidden rounded-xl border-4 border-white shadow-2xl">
                <img 
                  src={interiorImage} 
                  alt="Elegant restaurant interior look" 
                  className="w-full aspect-[4/3] object-cover hover:scale-105 transition duration-500"
                />
              </div>
              
              {/* Overlapping Absolute secondary Card */}
              <div className="absolute -bottom-10 -right-4 sm:-right-8 z-20 max-w-[280px] bg-[#2C1A04] text-cream p-6 rounded-lg shadow-xl border border-gold/20">
                <div className="flex items-center gap-2 mb-3">
                  <span className="p-1.5 bg-gold/10 rounded border border-gold/20 text-gold block">
                    <Music className="w-5 h-5" />
                  </span>
                  <span className="font-serif font-bold tracking-wide text-sm text-gold">Muğam Gecələri</span>
                </div>
                <p className="text-xs text-cream/80 leading-relaxed font-light">
                  Hər axşam saat 20:00-dan etibarən əsl Azərbaycan xalq sənəti olan Canlı Muğam sədaları altında qədim tarixi mühiti hiss edəcəksiniz.
                </p>
              </div>

              {/* Backing decorative border frame */}
              <div className="absolute -top-4 -left-4 w-full h-full border border-gold/30 rounded-xl z-0 pointer-events-none"></div>
            </motion.div>

            {/* Prose Text Column */}
            <motion.div 
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="lg:col-span-6 space-y-6"
            >
              <div className="space-y-2">
                <span className="text-gold font-bold tracking-widest text-xs uppercase block">ƏBƏDİ MİRAS, ƏKRƏM ATMOSFER</span>
                <h2 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight text-stone-dark relative">
                  Qala Divarının Təməl Hekayəsi
                </h2>
                <div className="w-16 h-1 bg-gold mt-2"></div>
              </div>

              <p className="text-stone-dark/80 text-sm sm:text-base leading-relaxed">
                Bakının ən qədim guşəsi sayılan İçərişəhərdə, əsrlər boyu tarixin keşiyində duran nəhəng Qala Divarlarının bilavasitə kənarında yerləşən restoranımız, sizə yalnız ləzzətli təamlar deyil, həm də canlı şahidlik hissi vədə edir. 
              </p>

              <p className="text-stone-dark/80 text-sm sm:text-base leading-relaxed">
                Konseptimizin əsas hərəkətverici qüvvəsi milli irsimizdir. İçəri girən andan etibarən sizi əhatə edən daş divarlar, tunc qab-qacaqlar və qundaqlı şamdanlar uzaq əsrlərin sehirli dastanlarını xatırladır. Terrasımızda isə qədim Şərq ab-havası ilə modern Bakının alovlu qüllələri birləşərək zamanlararası körpü yaradır.
              </p>

              {/* Multi points with micro icons */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-4">
                <div className="flex gap-2 items-start">
                  <div className="p-1 rounded bg-[#2C1A04] text-gold mt-0.5 pt-1 flex items-center">
                    <Check className="w-3.5 h-3.5" />
                  </div>
                  <div>
                    <h4 className="font-bold text-sm text-stone-dark">24 Saat Fasiləsiz Xidmət</h4>
                    <p className="text-xs text-stone-dark/60 leading-normal">Bakının hər anında, isti təndir və barlı kabab sizinlədir.</p>
                  </div>
                </div>

                <div className="flex gap-2 items-start">
                  <div className="p-1 rounded bg-[#2C1A04] text-gold mt-0.5 pt-1 flex items-center">
                    <Check className="w-3.5 h-3.5" />
                  </div>
                  <div>
                    <h4 className="font-bold text-sm text-stone-dark">Milli və Halal Məhsul</h4>
                    <p className="text-xs text-stone-dark/60 leading-normal">Bütün kəsimlər və göyərtilər hər səhər təzə gətirilir.</p>
                  </div>
                </div>

                <div className="flex gap-2 items-start">
                  <div className="p-1 rounded bg-[#2C1A04] text-gold mt-0.5 pt-1 flex items-center">
                    <Check className="w-3.5 h-3.5" />
                  </div>
                  <div>
                    <h4 className="font-bold text-sm text-stone-dark">Eleqant Terras & İsti Zallar</h4>
                    <p className="text-xs text-stone-dark/60 leading-normal">Həm fəsillərarası qorunalı qapalı zallar, həm də açıq terras.</p>
                  </div>
                </div>

                <div className="flex gap-2 items-start">
                  <div className="p-1 rounded bg-[#2C1A04] text-gold mt-0.5 pt-1 flex items-center">
                    <Check className="w-3.5 h-3.5" />
                  </div>
                  <div>
                    <h4 className="font-bold text-sm text-stone-dark">Premium Muğam Trio</h4>
                    <p className="text-xs text-stone-dark/60 leading-normal">Sənətkarlardan canlı klassik Azərbaycan muğam gecələri.</p>
                  </div>
                </div>
              </div>

            </motion.div>

          </div>
        </div>
      </section>

      {/* Interactive Grid Menu Section */}
      <section id="menu" className="py-24 bg-cream-dark relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          
          {/* Header centered info */}
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
            <span className="text-gold font-bold tracking-widest text-xs uppercase block">XALİS RESEPTLƏR</span>
            <h2 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight text-stone-dark">
              Zəngin Milli Qala Menyusu
            </h2>
            <div className="w-16 h-1 bg-gold mx-auto"></div>
            <p className="text-stone-dark/70 text-sm leading-relaxed">
              Mətbəximizin bütün təamları əsrlik kənd qaydalarından, təmiz kərə yağından və dağda yem yeyən mal-qaralardan ilhamlanaraq xüsusi sənətkarlıqla hazırlanır. Aşağıdakı kateqoriyalardan seçim edib menyumuzu gəzə bilərsiniz.
            </p>
          </div>

          {/* Interactive Category Filter bar */}
          <div className="flex flex-wrap justify-center gap-2 sm:gap-3 mb-10">
            {[
              { id: 'all', label: 'Bütün Təamlar' },
              { id: 'seher-yemeyi', label: 'Səhər Yeməyi' },
              { id: 'salatlar-mezeler', label: 'Salat & Məzələr' },
              { id: 'isti-yemekler', label: 'İsti Yeməklər' },
              { id: 'saclar', label: 'Saclar' },
              { id: 'kabablar', label: 'Milli Kabablar' },
              { id: 'desertler', label: 'Desertlər' },
              { id: 'ickiler', label: 'Alkoqolsuz İçkilər' },
              { id: 'spirtli-ickiler', label: 'Spirtli İçkilər' }
            ].map((cat) => (
              <button
                key={cat.id}
                onClick={() => { setActiveCategory(cat.id); setCurrentPage(1); }}
                className={`px-5 py-2.5 rounded-full text-xs sm:text-sm font-semibold tracking-wide border transition duration-300 ${
                  activeCategory === cat.id
                    ? 'bg-[#2C1A04] text-gold border-gold shadow-md'
                    : 'bg-white text-stone-dark border-stone-dark/10 hover:border-gold hover:bg-white'
                }`}
              >
                {cat.label}
              </button>
            ))}
          </div>

          {/* Menu Items Grid layout */}
          <motion.div 
            layout
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
          >
            <AnimatePresence mode="popLayout">
            {paginatedItems.map((item, index) => {
              const isFav = favorites.includes(item.id);
              return (
                <motion.div 
                  layout
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  transition={{ duration: 0.3 }}
                  key={item.id}
                  id={`menu-item-${item.id}`}
                  onClick={() => setSelectedMenuItem(item)}
                  className="bg-white rounded-xl shadow-md border border-stone-dark/5 overflow-hidden flex flex-col justify-between group cursor-pointer hover:shadow-xl hover:border-gold/30 hover:-translate-y-1 transition duration-300 relative"
                >
                  
                  {/* Decorative Special labels on Top absolute image */}
                  <div className="relative overflow-hidden aspect-[4/3] bg-stone-dark/10">
                    <img 
                      src={item.image} 
                      alt={item.name}
                      className="w-full h-full object-cover group-hover:scale-105 transition duration-500"
                    />
                    
                    {/* Dark gradient shadow inside image */}
                    <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent"></div>

                    {/* Badge row */}
                    <div className="absolute top-3 left-3 flex flex-col gap-1.5 z-10 font-sans">
                      {item.isChefSpecial && (
                        <span className="bg-gold text-stone-dark text-[10px] font-bold tracking-widest px-2.5 py-1 rounded uppercase flex items-center gap-1 shadow-md">
                          <Sparkles className="w-3 h-3" /> ŞEFİN SEÇİMİ
                        </span>
                      )}
                      {item.isPopular && (
                        <span className="bg-[#2C1A04] text-cream text-[10px] font-bold tracking-widest px-2.5 py-1 rounded uppercase flex items-center gap-1 shadow-md border border-gold/20">
                          <Award className="w-3 h-3 text-gold" /> POPULYAR
                        </span>
                      )}
                    </div>

                    {/* Interactive Heart (favorite button) strictly local */}
                    <button
                      onClick={(e) => toggleFavorite(item.id, e)}
                      className="absolute top-3 right-3 w-8 h-8 rounded-full bg-white/90 backdrop-blur-sm border border-stone-dark/5 flex items-center justify-center text-stone-dark hover:text-red-500 hover:scale-110 active:scale-90 shadow-md transition z-10 animate-inner"
                      aria-label="Sevimlilərə əlavə et"
                    >
                      <Heart className={`w-4 h-4 ${isFav ? 'fill-rose-600 text-rose-600' : 'text-stone-dark/60'}`} />
                    </button>

                    {/* Weight tag inside image bottom right */}
                    {item.weight && (
                      <span className="absolute bottom-3 right-3 text-white text-xs bg-black/50 backdrop-blur-sm px-2 py-0.5 rounded font-mono">
                        {item.weight}
                      </span>
                    )}
                  </div>

                  {/* Description Box Content */}
                  <div className="p-6 flex-1 flex flex-col justify-between space-y-4">
                    <div className="space-y-2">
                      <div className="flex justify-between items-start gap-2">
                        <h3 className="font-serif font-bold text-lg text-stone-dark group-hover:text-gold transition">
                          {item.name}
                        </h3>
                        <span className="font-serif text-lg font-bold text-stone-dark whitespace-nowrap bg-gold/10 px-2 py-0.5 rounded border border-gold/20">
                          {item.price} ₼
                        </span>
                      </div>
                      <p className="text-xs sm:text-sm text-stone-dark/70 line-clamp-2 leading-relaxed">
                        {item.description}
                      </p>
                    </div>

                    {/* Ingredient pills preview & interactive order hint */}
                    <div className="pt-2 border-t border-stone-dark/5 flex flex-wrap justify-between items-center text-xs text-stone-dark/60">
                      <span className="flex items-center gap-1 text-[11px] text-[#5E4121]">
                        <Coffee className="w-3.5 h-3.5 text-gold" /> Təbii inqrediyentlər
                      </span>
                      <span className="text-gold font-bold text-[11px] uppercase group-hover:translate-x-1 transition duration-150 block">ƏTRAFLI BAX →</span>
                    </div>

                  </div>

                </motion.div>
              );
            })}
            </AnimatePresence>
          </motion.div>

          {/* Pagination Controls */}
          {totalPages > 1 && (
            <div className="flex flex-col sm:flex-row justify-center items-center gap-4 mt-12 bg-transparent w-full mx-auto px-4 py-2">
              <div className="flex justify-center items-center gap-2 bg-white px-2 py-2 sm:px-4 sm:py-3 rounded-full shadow-md border border-stone-dark/10 max-w-full">
                <button
                  onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                  disabled={currentPage === 1}
                  className="w-10 h-10 shrink-0 rounded-full flex items-center justify-center border border-transparent hover:bg-stone-dark/5 transition disabled:opacity-30 disabled:hover:bg-transparent"
                >
                  &larr;
                </button>
                
                <div className="flex items-center gap-1.5 px-2 overflow-x-auto max-w-[60vw] sm:max-w-md hide-scrollbar">
                  {Array.from({ length: totalPages }, (_, i) => i + 1).map(page => (
                    <button
                      key={page}
                      onClick={() => setCurrentPage(page)}
                      className={`w-8 h-8 shrink-0 rounded-full text-sm font-semibold transition ${
                        currentPage === page
                          ? 'bg-gold text-stone-dark shadow'
                          : 'text-stone-dark hover:bg-stone-dark/5'
                      }`}
                    >
                      {page}
                    </button>
                  ))}
                </div>

                <button
                  onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                  disabled={currentPage === totalPages}
                  className="w-10 h-10 shrink-0 rounded-full flex items-center justify-center border border-transparent hover:bg-stone-dark/5 transition disabled:opacity-30 disabled:hover:bg-transparent"
                >
                  &rarr;
                </button>
              </div>
            </div>
          )}

          {/* Quick Special Combo Box design for tea session */}
          <div className="mt-16 bg-[#2C1A04] rounded-2xl border border-gold/30 p-8 sm:p-12 relative overflow-hidden text-cream shadow-xl">
            
            <div className="absolute right-0 top-0 bottom-0 opacity-10 hidden lg:block w-1/3">
              <img 
                src={teaImage} 
                alt="Samovar background ornament illustration" 
                className="w-full h-full object-cover filter saturate-50"
              />
            </div>

            <div className="max-w-2xl space-y-4 relative z-10">
              <span className="text-gold font-bold tracking-widest text-xs uppercase block">XÜSUSİ DƏYƏR</span>
              <h3 className="font-serif text-2xl sm:text-3xl font-bold">Əfsanəvi "Qala Divarı" Çay Dəstgahı</h3>
              <p className="text-sm sm:text-base text-cream/80 leading-relaxed">
                Qədim Içərişəhərdə qızmar samovardan süzülən kəklikotulu çay dəstgahı bizim əsas fəxrimizdir. Dadlı Baku paxlavası, xırda hil ilə bişmiş şəkərbura, ev üsulu kətə, mövsüm mürəbbələri (albalı, bütöv gilas, qoz), fıstıqlı assorti şokolad və ləbləbi ləzzətindən zövq alın.
              </p>
              
              <div className="flex flex-wrap items-center gap-6 pt-4">
                <div>
                  <span className="text-[10px] uppercase tracking-widest text-[#E9C967] font-semibold block">MÜNASİB PREMİUM QİYMƏT</span>
                  <span className="text-3xl font-serif font-bold text-gold">22.00 ₼</span>
                </div>
                <a 
                  href="tel:+994505555051"
                  className="bg-gold hover:bg-gold-light active:scale-95 text-stone-dark font-bold text-xs tracking-wider uppercase px-6 py-3.5 rounded flex items-center gap-1.5 transition"
                >
                  <Phone className="w-3.5 h-3.5" /> SİFARİŞ VER
                </a>
              </div>
            </div>
          </div>

        </div>
      </section>

      {/* Modern Bento Grid and Custom Slider Carousel Gallery */}
      <motion.section 
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 0.8 }}
        id="gallery" 
        className="py-24 bg-cream relative overflow-hidden"
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
            <span className="text-gold font-bold tracking-widest text-xs uppercase block">GÖZƏL XATİRƏLƏR</span>
            <h2 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight text-stone-dark">
              Restorandan Estetik Qalereya
            </h2>
            <div className="w-16 h-1 bg-gold mx-auto"></div>
            <p className="text-stone-dark/70 text-sm leading-relaxed">
              İstər açıq səma altındakı geniş terrasımız, istərsə də tağvari tarixin nəfəsini daşıyan qapalı zallarımız olsun. Hər bir guşədə müasir rahatlıqla qədim mühit birləşir.
            </p>
          </div>

          {/* Dynamic Slider/Carousel Layout Component */}
          <div className="relative max-w-5xl mx-auto p-4 bg-white rounded-2xl shadow-xl border border-stone-dark/5 overflow-hidden">
            
            {/* Sliding Image Frame */}
            <div className="relative h-[250px] sm:h-[450px] rounded-lg overflow-hidden z-0">
              <img 
                src={slides[currentSlide].image} 
                alt={slides[currentSlide].title} 
                className="w-full h-full object-cover transition duration-700 brightness-95"
              />
              <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 via-black/40 to-transparent p-6 text-white flex flex-col justify-end">
                <span className="text-gold font-bold text-xs tracking-widest uppercase mb-1 font-sans">Guşələrimiz • {currentSlide + 1} / {slides.length}</span>
                <h3 className="font-serif text-xl sm:text-2xl font-bold">{slides[currentSlide].title}</h3>
                <p className="text-xs sm:text-sm text-white/80 max-w-2xl mt-1 leading-relaxed hidden sm:block">{slides[currentSlide].desc}</p>
              </div>
            </div>

            {/* Slider Navigation Overlays */}
            <button 
              onClick={prevSlide}
              aria-label="Əvvəlki şəkil"
              className="absolute left-6 top-1/2 -translate-y-1/2 w-10 sm:w-12 h-10 sm:h-12 rounded-full bg-black/55 backdrop-blur-sm hover:bg-gold hover:text-stone-dark text-white flex items-center justify-center transition active:scale-90 z-20 focus:outline-none"
            >
              <ChevronLeft className="w-5 sm:w-6 h-5 sm:h-6" />
            </button>
            <button 
              onClick={nextSlide}
              aria-label="Növbəti şəkil"
              className="absolute right-6 top-1/2 -translate-y-1/2 w-10 sm:w-12 h-10 sm:h-12 rounded-full bg-black/55 backdrop-blur-sm hover:bg-gold hover:text-stone-dark text-white flex items-center justify-center transition active:scale-90 z-20 focus:outline-none"
            >
              <ChevronRight className="w-5 sm:w-6 h-5 sm:h-6" />
            </button>

            {/* Indicator dots */}
            <div className="flex justify-center gap-2 mt-4">
              {slides.map((_, idx) => (
                <button
                  key={idx}
                  onClick={() => setCurrentSlide(idx)}
                  className={`w-2.5 h-2.5 rounded-full transition ${currentSlide === idx ? 'bg-gold w-6' : 'bg-stone-dark/25'}`}
                  aria-label={`Slayd ${idx + 1}`}
                />
              ))}
            </div>

          </div>

          {/* Secondary Bento Grid gallery of delicious food details */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-8 max-w-5xl mx-auto">
            <div className="relative group overflow-hidden rounded-lg aspect-square bg-stone-dark/5">
              <img src={kebabImage} alt="Milli Kabab bişirilməsi" className="w-full h-full object-cover group-hover:scale-105 transition duration-500" />
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center transition p-4 text-center">
                <span className="text-white text-sm font-serif font-bold border-b border-gold/50 pb-1">Manqal sənəti</span>
              </div>
            </div>
            
            <div className="relative group overflow-hidden rounded-lg aspect-square bg-stone-dark/5">
              <img src={teaImage} alt="Zəngin armudu çay süfrəsi" className="w-full h-full object-cover group-hover:scale-105 transition duration-500" />
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center transition p-4 text-center">
                <span className="text-white text-sm font-serif font-bold border-b border-gold/50 pb-1">İncə Armudu Çay</span>
              </div>
            </div>

            <div className="relative group overflow-hidden rounded-lg aspect-square bg-stone-dark/5">
              <img src={sajImage} alt="Hərarətli quzu sacı dəmirlə" className="w-full h-full object-cover group-hover:scale-105 transition duration-500" />
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center transition p-4 text-center">
                <span className="text-white text-sm font-serif font-bold border-b border-gold/50 pb-1">Cızbız və Sac</span>
              </div>
            </div>

            <div className="relative group overflow-hidden rounded-lg aspect-square bg-stone-dark/5">
              <img src={heroImage} alt="Gecə ulduzlarının işığında terras" className="w-full h-full object-cover group-hover:scale-105 transition duration-500" />
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center transition p-4 text-center">
                <span className="text-white text-sm font-serif font-bold border-b border-gold/50 pb-1">Baku Alov Mənzərəsi</span>
              </div>
            </div>
          </div>

        </div>
      </motion.section>

      {/* Muğam Gecəsi Dedicated Info Block Section with fine graphics */}
      <section className="py-20 bg-cream relative z-10 overflow-hidden border-y border-gold/10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-[#FAF6EE] rounded-2xl border border-gold/20 p-8 sm:p-12 flex flex-col md:flex-row items-center justify-between gap-8 shadow-sm">
            
            <div className="flex gap-4 items-start max-w-2xl">
              <div className="p-4 bg-gold/10 border border-gold/30 text-gold rounded-full shrink-0">
                <Music className="w-8 h-8" />
              </div>
              <div className="space-y-2">
                <span className="text-[10px] bg-gold/20 text-stone-dark px-2 py-0.5 rounded-full font-bold uppercase tracking-wider inline-block font-sans">CANLI İFA GECƏLƏRİ</span>
                <h3 className="font-serif text-2xl font-bold text-stone-dark">Premium Muğam və Milli Musiqi İfaları</h3>
                <p className="text-xs sm:text-sm text-stone-dark/80 leading-relaxed">
                  Hər həftə sonu və bayram günlərində, Azərbaycanın tanınmış xanəndə və saz-tar sənətkarları "Qala Divarı" daxilində canlı muğam dəsfiyələri layihə edirlər. Qonaq olan bütün daxili və xarici qonaqlarımız üçün giriş tamamilə sərbəstdir.
                </p>
                <div className="flex flex-wrap items-center gap-x-6 gap-y-2 pt-2 text-xs font-semibold text-stone-dark/70 font-sans">
                  <span>📅 Cümə, Şənbə və Bazar</span>
                  <span>⏰ Başlanğıc: 20:00</span>
                  <span>🎷 Tar, Kamança, Qaval</span>
                </div>
              </div>
            </div>

            <div className="w-full md:w-auto shrink-0 flex flex-col gap-2 font-sans">
              <a 
                href="tel:+994505555051" 
                className="w-full md:w-auto text-center bg-[#2C1A04] hover:bg-stone-light text-[#E9C967] uppercase font-bold text-xs tracking-widest px-8 py-4 rounded-lg shadow-md transition flex items-center justify-center gap-2"
              >
                <Phone className="w-3.5 h-3.5" /> ƏLAQƏ SAXLA
              </a>
              <span className="text-[10px] text-center text-stone-dark/50">Əlavə şou və ya bilet ödənişi yoxdur.</span>
            </div>

          </div>
        </div>
      </section>

      {/* Google Maps Map Embed and Contact Details Card Area */}
      <motion.section 
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6 }}
        id="contact" className="py-24 bg-cream relative"
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
            <span className="text-gold font-bold tracking-widest text-xs uppercase block">BİZİ KƏŞF EDİN</span>
            <h2 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight text-stone-dark">
              Lokasiya və Giriş Yolları
            </h2>
            <div className="w-16 h-1 bg-gold mx-auto"></div>
            <p className="text-stone-dark/70 text-sm leading-relaxed">
              İçərişəhərdə, Kiçik Qala döngəsi 124 ünvanında yerləşirik. Qədim binaların mühitində bizi rahatlıqla tapmaq üçün aşağıdakı xəritədən istifadə edə bilərsiniz.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
            
            {/* Contact details left card */}
            <div className="lg:col-span-5 bg-[#2C1A04] text-cream rounded-2xl p-6 sm:p-10 border border-gold/20 flex flex-col justify-between shadow-xl">
              
              <div className="space-y-6">
                <div>
                  <span className="text-gold text-xs font-bold tracking-widest uppercase block mb-1">RƏSMİ RESTORAN</span>
                  <h3 className="font-serif text-3xl font-bold text-cream">Qala Divarı</h3>
                  <div className="w-12 h-1 bg-gold mt-2"></div>
                </div>

                <div className="space-y-4">
                  
                  {/* Address element */}
                  <div className="flex gap-4 items-start">
                    <div className="p-2 bg-gold/10 text-gold rounded border border-gold/20 mt-1">
                      <MapPin className="w-5 h-5" />
                    </div>
                    <div>
                      <h4 className="font-serif font-bold text-sm tracking-wide text-gold">Ünvan</h4>
                      <p className="text-xs sm:text-sm text-cream/80 mt-1 leading-normal">
                        Kiçik Qala döngəsi 124, İçərişəhər, Bakı 1001, Azərbaycan.
                      </p>
                      <span className="text-[10px] text-cream/50 mt-1 block font-mono">Qoşa Qala Qapılarından gələn sol döngə</span>
                    </div>
                  </div>

                  {/* Operational Hours */}
                  <div className="flex gap-4 items-start">
                    <div className="p-2 bg-gold/10 text-gold rounded border border-gold/20 mt-1">
                      <Clock className="w-5 h-5" />
                    </div>
                    <div>
                      <h4 className="font-serif font-bold text-sm tracking-wide text-gold">İş saatları</h4>
                      <p className="text-xs sm:text-sm text-cream/80 mt-1 leading-normal font-sans">
                        Həftənin 7 günü, 24 saat fasiləsiz fəaliyyət (24/7).
                      </p>
                    </div>
                  </div>

                  {/* Hot contact */}
                  <div className="flex gap-4 items-start">
                    <div className="p-2 bg-gold/10 text-gold rounded border border-gold/20 mt-1">
                      <Phone className="w-5 h-5" />
                    </div>
                    <div>
                      <h4 className="font-serif font-bold text-sm tracking-wide text-gold">Telefon & Sifariş</h4>
                      <a href="tel:+994505555051" className="text-xs sm:text-sm text-cream/90 hover:text-gold block mt-1 leading-normal font-bold">
                        +994 50 555 50 51
                      </a>
                    </div>
                  </div>

                </div>
              </div>

              {/* Google rate highlights on bottom */}
              <div className="pt-8 border-t border-cream/10 mt-8 flex justify-between items-center text-xs font-sans">
                <div>
                  <span className="text-[10px] uppercase tracking-widest text-[#E9C967] block">GOOGLE REYTİNQ</span>
                  <div className="flex items-center gap-1.5 mt-1">
                    <Star className="w-4 h-4 text-gold fill-gold" />
                    <span className="font-black text-cream text-sm">4.8</span>
                    <span className="text-cream/55">(350+ rəy)</span>
                  </div>
                </div>
                <div className="text-right">
                  <span className="text-[10px] uppercase tracking-widest text-[#E9C967] block">METRO LOKASİYA</span>
                  <span className="text-cream/80 font-medium block mt-1">İçərişəhər metrosu (5 dəq pəncə)</span>
                </div>
              </div>

            </div>

            {/* Interactive map right size */}
            <div className="lg:col-span-7 rounded-2xl overflow-hidden border border-stone-dark/15 shadow-xl relative min-h-[350px]">
              <iframe
                title="Qala Divarı Restaurant Google Maps"
                src="https://maps.google.com/maps?q=Qala+Divar%C4%B1+Bak%C4%B1&t=&z=17&ie=UTF8&iwloc=&output=embed"
                width="100%"
                height="100%"
                style={{ border: 0 }}
                allowFullScreen={true}
                loading="lazy"
                referrerPolicy="no-referrer-when-downgrade"
                className="absolute inset-0 w-full h-full"
              ></iframe>
            </div>

          </div>

        </div>
      </motion.section>

      {/* Styled Interactive Footer */}
      <footer id="footer-section" className="bg-[#1C0F01] text-cream border-t border-gold/15 py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          
          <div className="grid grid-cols-1 md:grid-cols-12 gap-8 pb-10 border-b border-cream/10">
            
            {/* Logo and brief conceptual statement */}
            <div className="md:col-span-4 space-y-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-full overflow-hidden border border-gold flex items-center justify-center shrink-0 bg-white">
                  <img src="https://cdn.cafepos.az/storage/restaurants/64621e1e0c827.jpg" alt="Qala Divarı Logo" className="w-full h-full object-cover" />
                </div>
                <span className="font-serif text-xl font-bold tracking-wider text-cream">QALA DİVARI</span>
              </div>
              <p className="text-xs text-cream/70 leading-relaxed font-light mt-4">
                Əsl Azərbaycan milli mətbəxi təamlarını unikal İçərişəhər qala mühitində dadsınlar deyə, biz hər an - 24/7 qapılarımızı qonaqlarımızın üzünə açırıq.
              </p>
              <div className="flex items-center gap-3 text-xs text-gold font-semibold pt-1 font-sans">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
                <span>● İNDİ AÇIQDIR (24/7)</span>
              </div>
              
              <div className="flex items-center gap-3 mt-6 pt-4">
                <a 
                  href="https://www.instagram.com/qala_divari/" 
                  target="_blank" 
                  rel="noopener noreferrer" 
                  className="w-10 h-10 rounded-full bg-[#2C1A04] border border-gold/30 hover:border-gold hover:bg-gold hover:text-stone-dark flex items-center justify-center text-gold transition duration-300"
                  aria-label="Instagram Səhifəmiz"
                >
                  <Instagram className="w-4 h-4" />
                </a>
                <a 
                  href="tel:+994505555051" 
                  className="w-10 h-10 rounded-full bg-[#2C1A04] border border-gold/30 hover:border-gold hover:bg-gold hover:text-stone-dark flex items-center justify-center text-gold transition duration-300"
                  aria-label="Bizə Zəng Edin"
                >
                  <Phone className="w-4 h-4" />
                </a>
              </div>
            </div>

            {/* Faster Navigate options */}
            <div className="md:col-span-4 space-y-4 font-sans">
              <h4 className="font-serif font-bold text-gold tracking-wider text-sm font-semibold">Naviqasiya</h4>
              <div className="grid grid-cols-2 gap-2 text-xs block">
                <a href="#home" className="text-cream/70 hover:text-gold transition">Ana Səhifə</a>
                <a href="#our-history" className="text-cream/70 hover:text-gold transition">Haqqımızda</a>
                <a href="#menu" className="text-cream/70 hover:text-gold transition">Milli Menyu</a>
                <a href="#gallery" className="text-cream/70 hover:text-gold transition">Qalereya</a>
                <a href="#contact" className="text-cream/70 hover:text-gold transition">Əlaqə</a>
              </div>
            </div>

            {/* Featured menus highlighted */}
            <div className="md:col-span-4 space-y-4">
              <h4 className="font-serif font-bold text-gold tracking-wider text-sm font-semibold">Məşhur Təamlarımız</h4>
              <ul className="space-y-2 text-xs text-cream/70 font-light font-sans">
                <li>• Quzu Ətindən Grand Sac (26₼)</li>
                <li>• "Qala Divarı" Premium Kabab (38₼)</li>
                <li>• Samovar Çayı Dəstgahı (22₼)</li>
                <li>• İçi pütöv Qarabağ Kətəsi (6₼)</li>
              </ul>
            </div>

          </div>

          <div className="pt-8 flex flex-col sm:flex-row justify-between items-center text-xs text-cream/50 gap-4 mt-2 font-sans">
            <span>© {new Date().getFullYear()} Qala Divarı Restoranı. Bütün hüquqlar qorunur.</span>
            <div className="flex gap-4">
              <a href="#home" className="hover:text-gold transition">İstifadə Şərtləri</a>
              <a href="#contact" className="hover:text-gold transition">Lokasiya Yardım</a>
            </div>
          </div>

        </div>
      </footer>

      {/* Dynamic Detail Modal for individual Selected Menu Item */}
      <AnimatePresence>
      {selectedMenuItem && (
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          id="menu-detail-modal" 
          className="fixed inset-0 bg-stone-dark/80 backdrop-blur-sm z-50 flex items-center justify-center p-4"
        >
          <motion.div 
            initial={{ scale: 0.9, opacity: 0, y: 30 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.9, opacity: 0, y: 30 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
            className="bg-white text-stone-dark max-w-lg w-full rounded-2xl overflow-hidden shadow-2xl relative border border-gold/20 flex flex-col max-h-[90vh]"
          >
            
            {/* Close button modal */}
            <button 
              onClick={() => setSelectedMenuItem(null)}
              className="absolute top-4 right-4 w-9 h-9 rounded-full bg-black/40 backdrop-blur-sm text-white hover:bg-gold hover:text-stone-dark flex items-center justify-center z-10 transition duration-150"
              aria-label="Bağla"
            >
              <X className="w-5 h-5" />
            </button>

            {/* Detail image of individual dish */}
            <div className="relative aspect-[16/10]">
              <img 
                src={selectedMenuItem.image} 
                alt={selectedMenuItem.name} 
                className="w-full h-full object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/20 to-transparent"></div>
              
              <div className="absolute bottom-4 left-6 right-6 text-white font-sans">
                <span className="text-[10px] bg-gold text-stone-dark px-2.5 py-0.5 rounded font-bold uppercase tracking-wider items-center gap-1 inline-flex shadow-sm">
                  {selectedMenuItem.category === 'isti-yemekler' ? 'İsti Yemək' : 
                   selectedMenuItem.category === 'kabablar' ? 'Kabab' :
                   selectedMenuItem.category === 'cay-destgahi' ? 'Çay Dəstgahı' : 'Desert'}
                </span>
                <h3 className="font-serif text-2xl font-bold mt-1.5">{selectedMenuItem.name}</h3>
              </div>
            </div>

            {/* Scrollable details contents */}
            <div className="p-6 space-y-4 overflow-y-auto font-sans">
              
              {/* Price and weight info */}
              <div className="flex justify-between items-center bg-cream p-3 rounded-lg border border-stone-dark/5">
                <div>
                  <span className="text-[9px] uppercase tracking-widest text-[#5E4121] font-semibold block">Porsiya qiyməti</span>
                  <span className="text-xl font-serif font-black text-[#2C1A04]">{selectedMenuItem.price}.00 ₼</span>
                </div>
                {selectedMenuItem.weight && (
                  <div className="text-right">
                    <span className="text-[9px] uppercase tracking-widest text-[#5E4121] font-semibold block">Çəkisi / Həcmi</span>
                    <span className="text-sm font-semibold text-[#5E4121]">{selectedMenuItem.weight}</span>
                  </div>
                )}
              </div>

              {/* Main text description */}
              <p className="text-xs sm:text-sm text-stone-dark/75 leading-relaxed font-light font-sans">
                {selectedMenuItem.description}
              </p>

              {/* Ingredient list lists */}
              {selectedMenuItem.ingredients && selectedMenuItem.ingredients.length > 0 && (
                <div className="space-y-1.5 pt-2">
                  <span className="text-[10px] uppercase tracking-wider text-gold font-bold block">TƏRKİB DETALLARI:</span>
                  <div className="flex flex-wrap gap-1.5">
                    {selectedMenuItem.ingredients.map((ing) => (
                      <span key={ing} className="bg-cream-dark text-[#2C1A04] text-[11px] font-medium px-2.5 py-1 rounded">
                        • {ing}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Action buttons inside detail */}
              <div className="pt-4 flex gap-3">
                <button
                  type="button"
                  onClick={() => setSelectedMenuItem(null)}
                  className="flex-1 py-3 text-center border font-semibold text-xs tracking-widest rounded-lg text-stone-dark border-stone-dark/15 hover:bg-cream transition font-sans uppercase"
                >
                  MENYUYA QAYIT
                </button>
                <a
                  href="tel:+994505555051"
                  className="flex-1 py-3 text-center bg-gold hover:bg-gold-light text-stone-dark font-bold text-xs tracking-widest uppercase rounded-lg shadow transition flex items-center justify-center gap-1.5 font-sans"
                >
                  <Phone className="w-3.5 h-3.5" /> SİFARİŞ ET
                </a>
              </div>

            </div>

          </motion.div>
        </motion.div>
      )}
      </AnimatePresence>

    </div>
  );
}
